backend:
  name: github
  repo: falcodeuy/falcode-web
  branch: main
  base_url: https://falcode.dev

media_folder: "static/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime" }
      - { label: "Language", name: "lang", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Authors", name: "authors", widget: "list" }