backend:
  name: github
  repo: falcodeuy/falcode-web
  branch: main
  base_url: https://falcode.dev
  auth_endpoint: api/auth

publish_mode: editorial_workflow

media_folder: "static/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Updated At", name: "updatedAt", widget: "datetime", required: false }
      - { label: "Original Language", name: "lang", widget: "select", options: ["es", "en"] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "select"
          options:
            - "AI"
            - "Architecture"
            - "Automation"
            - "Cloud"
            - "Cybersecurity"
            - "Data"
            - "DevOps"
            - "Mobile"
            - "Product"
            - "UI/UX"
            - "Web Development"
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Credits & sources"
        name: "references"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "URL", name: "url", widget: "string", required: false }
          - { label: "Detail", name: "detail", widget: "text", required: false }
      - label: "Authors"
        name: "authors"
        widget: "list"
        field:
          name: "author"
          label: "Author"
          widget: "select"
          options:
            - "Fausto Márquez"
            - "Crhistyan Silva"
            - "Leandro Paz"
          required: true